-- Clean database
DROP TABLE ROLES_PRIVILEGES IF EXISTS;
DROP TABLE USERS_ROLES IF EXISTS;
DROP TABLE ROLES IF EXISTS;
DROP TABLE PRIVILEGE IF EXISTS;
DROP TABLE CLICK IF EXISTS;
DROP TABLE ADVERTISING_ACCESS IF EXISTS;
DROP TABLE SHORTURL IF EXISTS;
DROP TABLE USER IF EXISTS;

-- User
CREATE TABLE USER(
  ID		        BIGINT IDENTITY,                -- Key
  FIRSTNAME		  VARCHAR(1024) NOT NULL,				  -- First name
  LASTNAME      VARCHAR(1024) NOT NULL,         -- Surname
  EMAIL 	      VARCHAR(1024) NOT NULL UNIQUE,  -- Email
  PASSWORD		  VARCHAR(60)   NOT NULL				  -- Password
);

-- Roles
CREATE TABLE ROLES(
  ID		BIGINT IDENTITY,        -- Key
  NAME	VARCHAR(1024) NOT NULL	-- Rol name
);

-- Privileges
CREATE TABLE PRIVILEGE(
  ID		BIGINT IDENTITY,        -- Key
  NAME	VARCHAR(1024) NOT NULL	-- Privilege name
);

-- User roles
CREATE TABLE USERS_ROLES(
  USER_ID 	BIGINT NOT NULL,	-- Foreing key
  ROLE_ID 	BIGINT NOT NULL,  -- Foreing key
  FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)	ON UPDATE CASCADE ON DELETE CASCADE
);

-- Role privileges
CREATE TABLE ROLES_PRIVILEGES(
  ROLE_ID 	    BIGINT NOT NULL,	    -- Foreing key
  PRIVILEGE_ID 	BIGINT NOT NULL,	-- Foreing key
  FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE(ID)	ON UPDATE CASCADE ON DELETE CASCADE
);

-- ShortURL
CREATE TABLE SHORTURL(
	HASH		                VARCHAR(30) PRIMARY KEY,	-- Key
	TARGET		              VARCHAR(1024),				    -- Original URL
  URI                     VARCHAR(1024),            -- URI
	CREATED 	              TIMESTAMP,					      -- Creation date
	OWNER		                BIGINT NOT NULL,				      -- User id
	IP			                VARCHAR(20),				      -- IP
	COUNTRY		              VARCHAR(50),				      -- Country
  SAFE		                BOOLEAN,					-- Safe target
  LASTCHECKSAFEDATE       TIMESTAMP,       -- Last check if url is safe
  AVAILABLE		            BOOLEAN,					-- Available target
  LASTCHECKAVAILABLEDATE  TIMESTAMP,    -- Last check if url is available
--  FOREIGN KEY (OWNER) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Access to bypass advertising
CREATE TABLE ADVERTISING_ACCESS(
  ID      VARCHAR(36) PRIMARY KEY,
  HASH    VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES SHORTURL(HASH),	      -- Foreing key
  ACCESS  BOOLEAN     NOT NULL   -- Access to uri (0 if advertising already seen, 1 if has access)
);

-- Click
CREATE TABLE CLICK(
  ID 			  BIGINT IDENTITY,		-- KEY
	HASH 		  VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES SHORTURL(HASH),	-- Foreing key
	CREATED 	TIMESTAMP,					-- Creation date
	REFERRER	VARCHAR(1024),			-- Traffic origin
	BROWSER		VARCHAR(50),				-- Browser
	PLATFORM	VARCHAR(50),				-- Platform
	IP			  VARCHAR(20),				-- IP
	COUNTRY		VARCHAR(50)					-- Country
);

CREATE TABLE SYSTEM_CPU_USAGE(
  TIME BIGINT PRIMARY KEY,
  USAGE DOUBLE NOT NULL
);

CREATE TABLE SYSTEM_RAM_USAGE(
  TIME BIGINT PRIMARY KEY,
  USAGE DOUBLE NOT NULL
);